# Generated by Django 5.0.6 on 2025-08-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('s3_key', models.CharField(blank=True, max_length=500, verbose_name='Objeto S3/MinIO')),
                ('tamanho_b', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('crs', models.CharField(blank=True, max_length=64)),
                ('bounds', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('ready', 'Pronto'), ('error', 'Erro')], default='new', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cog', 'Gerar COG'), ('thumb', 'Gerar Thumbnail'), ('tiler', 'Publicar no Tiler'), ('odm', 'Processar no ODM')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Executando'), ('done', 'Concluído'), ('error', 'Erro')], default='queued', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='catalogo.dataset')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
