# Generated by Django 5.0.6 on 2025-08-18 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição (opcional)')),
                ('data_voo', models.DateField(blank=True, null=True, verbose_name='Data do voo')),
                ('plataforma', models.CharField(blank=True, max_length=120, verbose_name='Plataforma (drone)')),
                ('camera_modelo', models.CharField(blank=True, max_length=120, verbose_name='Modelo da câmera')),
                ('camera_tipo', models.CharField(choices=[('RGB', 'RGB'), ('MS', 'Multiespectral'), ('RGB_MS', 'RGB + Multiespectral')], default='RGB', max_length=10, verbose_name='Tipo de câmera')),
                ('georef', models.CharField(choices=[('NONE', 'Sem RTK/PPK'), ('RTK_FIXED', 'RTK (Fix)'), ('RTK_FLOAT', 'RTK (Float)'), ('PPK', 'PPK')], default='NONE', max_length=12, verbose_name='Georreferenciamento')),
                ('epsg', models.CharField(blank=True, help_text='Ex.: "EPSG:31983"', max_length=32, verbose_name='EPSG')),
                ('altura_voo_m', models.FloatField(blank=True, null=True, verbose_name='Altura de voo (m)')),
                ('gsd_cm', models.FloatField(blank=True, null=True, verbose_name='GSD (cm/pixel)')),
                ('overlap_frontal', models.PositiveSmallIntegerField(blank=True, help_text='0–100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overlap frontal (%)')),
                ('overlap_lateral', models.PositiveSmallIntegerField(blank=True, help_text='0–100%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overlap lateral (%)')),
                ('usa_gcp', models.BooleanField(default=False, verbose_name='Usa GCP')),
                ('gcp_csv', models.FileField(blank=True, help_text='Cabeçalho típico: label, x, y, z, lon, lat, alt (ou conforme template da plataforma).', null=True, upload_to='gcps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])], verbose_name='Arquivo GCP (CSV/TXT)')),
                ('prod_ortomosaico', models.BooleanField(default=True, verbose_name='Ortomosaico')),
                ('prod_dsm', models.BooleanField(default=False, verbose_name='DSM')),
                ('prod_dtm', models.BooleanField(default=False, verbose_name='DTM')),
                ('prod_nuvem_pts', models.BooleanField(default=False, verbose_name='Nuvem de pontos')),
                ('prod_contornos', models.BooleanField(default=False, verbose_name='Curvas de nível')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Opções avançadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['owner', 'criado_em'], name='projetos_pr_owner_i_1e1feb_idx')],
            },
        ),
    ]
