# Generated by Django 5.0.6 on 2025-08-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('DEFINICOES', 'Em definições'), ('AGUARDANDO_UPLOAD', 'Aguardando upload'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], db_index=True, default='DEFINICOES', max_length=24, verbose_name='Status'),
        ),
    ]
