# Generated by Django 5.0.6 on 2025-08-19 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='gcp_csv',
            field=models.FileField(blank=True, help_text='Cabeçalho típico: label, x, y, z, lon, lat, alt (ou conforme template).', null=True, upload_to='gcps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])], verbose_name='Arquivo GCP (CSV/TXT)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('DEFINICOES', 'Em definições'), ('AGUARDANDO_UPLOAD', 'Aguardando upload'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='DEFINICOES', max_length=24, verbose_name='Status'),
        ),
    ]
